// src/fontawesome-check.tsx
import React, { Component } from "react";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import { IconProp } from "@fortawesome/fontawesome-svg-core";

export class FontawesomeCheck extends Component<IProps, IState> {
  render() {
    const iconSet: IconProp = (this.props.on
      ? ["fas", "check-circle"]
      : ["far", "check-circle"]);
    return (
      <FontAwesomeIcon className={this.props.className}
        icon={iconSet}></FontAwesomeIcon>
    );
  }
}

interface IProps {
  className?: string;
  on: boolean;
};
type IState = {};

// src/FontawesomeCheck.vue
<template>
  <font-awesome-icon v-if="on" :icon="['fas', 'check-circle']" />
  <font-awesome-icon v-else :icon="['far', 'check-circle']" />
</template>

<script>
import { FontAwesomeIcon } from "@fortawesome/vue-fontawesome";

export default {
  components: { FontAwesomeIcon },
  props: {
    on: Boolean,
  },
};
</script>
