// src/record-selection.tsx
import React, { Component } from "react";
import { FontawesomeCheck } from "./fontawesome-check";

export class RecordSelection extends Component<IProps, IState> {
  constructor(props: IProps) {
    super(props);

    this.audioToggle = this.audioToggle.bind(this);
    this.cameraToggle = this.cameraToggle.bind(this);
    this.screenToggle = this.screenToggle.bind(this);
  }

  audioToggle() {
    this.emitRequest({
      audio: !this.props.audio,
      camera: this.props.camera,
      screen: this.props.screen,
    });
  }

  cameraToggle() {
    this.emitRequest({
      audio: this.props.audio,
      camera: !this.props.camera,
      screen: this.props.screen,
    });
  }

  screenToggle() {
    this.emitRequest({
      audio: this.props.audio,
      camera: this.props.camera,
      screen: !this.props.screen,
    });
  }

  emitRequest(request: SelectionChangeRequest) {
    this.props.onSelectionChange(request);
  }

  render() {
    const cameraClasses = [
      "btn btn-lg px-4",
      (this.props.camera ? "btn-secondary" : "btn-outline-secondary"),
    ];
    const audioClasses = [
      "btn btn-lg px-4",
      (this.props.audio ? "btn-secondary" : "btn-outline-secondary"),];
    const screenClasses = [
      "btn btn-lg px-4",
      (this.props.screen ? "btn-secondary" : "btn-outline-secondary"),];

    return (
      <div>
        <button
          type="button"
          className={cameraClasses.join(" ")}
          onClick={this.cameraToggle}
        >
          <FontawesomeCheck className="me-2"
            on={this.props.camera} />Camera
        </button>

        <button
          type="button"
          className={audioClasses.join(" ")}
          onClick={this.audioToggle}
        >
          <FontawesomeCheck className="me-2"
            on={this.props.audio} />Audio
        </button>

        <button
          type="button"
          className={screenClasses.join(" ")}
          onClick={this.screenToggle}
        >
          <FontawesomeCheck className="me-2"
            on={this.props.screen} />Screen
        </button>
      </div>
    );
  }
}

type IProps = {
  audio: boolean;
  camera: boolean;
  onSelectionChange: OnSelectionChangeCallback;
  screen: boolean;
};
type IState = {};

type OnSelectionChangeCallback = (request: SelectionChangeRequest) => void;
type SelectionChangeRequest = {
  audio: boolean;
  camera: boolean;
  screen: boolean;
};

// src/RecordSelection.vue
<template>
  <button
    type="button"
    class="btn btn-lg px-4"
    :class="{ 'btn-outline-secondary': !camera, 'btn-secondary': camera }"
    @click="cameraToggle"
  >
    <font-awesome-check class="me-2" :on="camera" />Camera
  </button>

  <button
    type="button"
    class="btn btn-lg px-4"
    :class="{ 'btn-outline-secondary': !audio, 'btn-secondary': audio }"
    @click="audioToggle"
  >
    <font-awesome-check class="me-2" :on="audio" />Audio
  </button>

  <button
    type="button"
    class="btn btn-lg px-4"
    :class="{ 'btn-outline-secondary': !screen, 'btn-secondary': screen }"
    @click="screenToggle"
  >
    <font-awesome-check class="me-2" :on="screen" />Screen
  </button>
</template>

<script>
import FontAwesomeCheck from "./FontawesomeCheck.vue";

export default {
  components: { FontAwesomeCheck },
  emits: ["selectionRequest"],
  methods: {
    audioToggle() {
      this.emitRequest({
        audio: !this.audio,
        camera: this.camera,
        screen: this.screen,
      });
    },
    cameraToggle() {
      this.emitRequest({
        audio: this.audio,
        camera: !this.camera,
        screen: this.screen,
      });
    },
    screenToggle() {
      this.emitRequest({
        audio: this.audio,
        camera: this.camera,
        screen: !this.screen,
      });
    },
    emitRequest(request) {
      this.$emit("selectionRequest", request);
    },
  },
  props: {
    audio: Boolean,
    camera: Boolean,
    screen: Boolean,
  },
};
</script>
