// src/SelectionPreview.vue
<template>
  <video-preview v-show="showVideo" :stream="videoStream"></video-preview>
  <audio-preview
    v-show="showAudio"
    :level="audioLevel"
    :max="audioMax"
  ></audio-preview>
</template>

<script>
import AudioPreview from "./AudioPreview.vue";
import VideoPreview from "./VideoPreview.vue";

export default {
  components: { AudioPreview, VideoPreview },
  props: {
    audioLevel: Number,
    audioMax: Number,
    showAudio: Boolean,
    showVideo: Boolean,
    videoStream: Object,
  },
};
</script>

// src/selection-preview.tsx
import React, { Component } from "react";
import { AudioPreview } from "./audio-preview";
import { VideoPreview } from "./video-preview";

export class SelectionPreview extends Component<IProps, IState> {
  render() {
    const videoPreview = (this.props.videoStream
      ? <VideoPreview stream={this.props.videoStream}></VideoPreview>
      : <></>
    );
    const audioPreview = (this.props.showAudio
      ? <AudioPreview level={this.props.audioLevel}></AudioPreview>
      : <></>
    );

    return (
      <div>{videoPreview}{audioPreview}</div>
    );
  }
}

type IProps = {
  audioLevel: number;
  showAudio: boolean;
  videoStream?: MediaStream;
};
type IState = {};
