// src/VideoPreview.vue
<template>
  <video ref="video" autoplay="autoplay"></video>
</template>

<script>
export default {
  props: {
    stream: Object,
  },
  watch: {
    stream() {
      if (this.stream) {
        this.$refs.video.srcObject = this.stream;
      } else {
        this.$refs.video.srcObject = null;
      }
    },
  },
};
</script>

// src/video-preview.tsx
import React, { Component } from "react";

export class VideoPreview extends Component<IProps, IState> {
  videoRef(element: HTMLVideoElement) {
    element.srcObject = this.props.stream;
  }

  render() {
    return (
      <video
        ref={this.videoRef}
        autoPlay={true}></video>
    );
  }
}

type IProps = {
  stream: MediaStream;
};
type IState = {};
